SistemaPanera.Application/Controllers/ComprasController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaPanera.Application.Models;
using SistemaPanera.Application.Models.ViewModels;
using SistemaPanera.BLL.Service;
using SistemaPanera.Models;
using System.Diagnostics;
using System.Text.Json.Serialization;
using System.Text.Json;

namespace SistemaPanera.Application.Controllers
{
    [Authorize]
    public class ComprasController : Controller
    {
        private readonly ICompraService _ComprasService;

        public ComprasController(ICompraService ComprasService)
        {
            _ComprasService = ComprasService;
        }

        public IActionResult Index()
        {
            return View();
        }



        [HttpGet]
        public async Task<IActionResult> Lista(int IdUnidadNegocio, int IdLocal)
        {
            try
            {
                var Compras = await _ComprasService.ObtenerTodos();

                var lista = Compras.Select(c => new VMCompra
                {
                    Id = c.Id,
                    IdUnidadNegocio = c.IdUnidadNegocio,
                    Fecha = c.Fecha,
                    IdLocal = c.IdLocal,
                    IdProveedor = c.IdProveedor,
                    NumeroOrden = c.NumeroOrden,
                    UnidadNegocio = c.IdUnidadNegocioNavigation.Nombre,
                    Local = c.IdLocalNavigation.Nombre,
                    Costo = c.Costo
                }).Where(x => x.IdUnidadNegocio == IdUnidadNegocio || IdUnidadNegocio == -1 && x.IdLocal == IdLocal || IdLocal == -1).ToList();

                return Ok(lista);
            }
            catch (Exception ex)
            {
                return Ok(null);
            }
        }


        [HttpPost]
        public async Task<IActionResult> Insertar([FromBody] VMCompra model)
        {
            var Compras = new Compra
            {
                Id = model.Id,
                IdUnidadNegocio = model.IdUnidadNegocio,
                Fecha = model.Fecha,
                IdLocal = model.IdLocal,
                IdProveedor = model.IdProveedor,
                NumeroOrden = model.NumeroOrden,

            };

            bool respuesta = await _ComprasService.Insertar(Compras);

            List<ComprasDetalle> pedidosInsumo = new List<ComprasDetalle>();

            // Agregar los pagos de clientes
            if (model.ComprasDetalles != null && model.ComprasDetalles.Any())
            {
                foreach (var insumo in model.ComprasDetalles)
                {
                    var nuevoInsumo = new ComprasDetalle
                    {
                        IdCompra = Compras.Id,
                        IdInsumo = insumo.IdInsumo,
                        CostoUnitario = insumo.CostoUnitario,
                        SubTotal = insumo.SubTotal,
                        Cantidad = insumo.Cantidad,
                    };
                    pedidosInsumo.Add(nuevoInsumo);
                }
            }

            bool respInsumos = await _ComprasService.InsertarInsumos(pedidosInsumo);

            return Ok(new { valor = respuesta });
        }

        [HttpPut]
        public async Task<IActionResult> Actualizar([FromBody] VMCompra model)
        {
            var Compras = new Compra
            {
                Id = model.Id,
                IdUnidadNegocio = model.IdUnidadNegocio,
                Fecha = model.Fecha,
                IdLocal = model.IdLocal,
                IdProveedor = model.IdProveedor,
                NumeroOrden = model.NumeroOrden,

            };

            bool respuesta = await _ComprasService.Actualizar(Compras);

            List<ComprasDetalle> ComprasInsumo = new List<ComprasDetalle>();

            // Agregar los pagos de clientes
            if (model.ComprasDetalles != null && model.ComprasDetalles.Any())
            {
                foreach (var insumo in model.ComprasDetalles)
                {
                    var nuevoInsumo = new ComprasDetalle
                    {
                        Cantidad = insumo.Cantidad,
                        CostoUnitario = insumo.CostoUnitario,
                        IdInsumo = insumo.IdInsumo,
                        IdCompra = insumo.IdCompra,
                        SubTotal = insumo.SubTotal,
                    };
                    ComprasInsumo.Add(nuevoInsumo);
                }
            }

            bool respproductos = await _ComprasService.InsertarInsumos(ComprasInsumo);

            return Ok(new { valor = respuesta });
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int id)
        {
            bool respuesta = await _ComprasService.Eliminar(id);

            return StatusCode(StatusCodes.Status200OK, new { valor = respuesta });
        }

        [HttpGet]
        public async Task<IActionResult> EditarInfo(int id)
        {
            Dictionary<string, object> result = new Dictionary<string, object>();

            if (id > 0)
            {

                var model = await _ComprasService.Obtener(id);

                var Compra = new VMCompra
                {
                    Id = model.Id,
                    IdUnidadNegocio = model.IdUnidadNegocio,
                    Fecha = DateTime.Now,
                    IdLocal = model.IdLocal,
                    IdProveedor = model.IdProveedor,
                    NumeroOrden = model.NumeroOrden,

                };

                var ComprasInsumos = await _ComprasService.ObtenerInsumos(id);


                var insumosJson = ComprasInsumos.Select(p => new VMComprasDetalle
                {
                    Id = p.Id,

                    Cantidad = p.Cantidad,
                    CostoUnitario = p.CostoUnitario,
                    IdInsumo = p.IdInsumo,
                    Nombre = p.IdInsumoNavigation.Descripcion.ToString(),
                    IdCompra = p.IdCompra,
                    SubTotal = p.SubTotal,
                }).ToList();



                result.Add("Compra", Compra);
                result.Add("Insumos", insumosJson);

                // Serialize with ReferenceHandler.Preserve to handle circular references
                var jsonOptions = new JsonSerializerOptions
                {
                    ReferenceHandler = ReferenceHandler.Preserve
                };

                return Ok(System.Text.Json.JsonSerializer.Serialize(result, jsonOptions));
            }

            return Ok(new { });
        }





        public async Task<IActionResult> NuevoModif(int? id)
        {
            if (id != null)
            {
                ViewBag.data = id;
            }
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaPanera.Application/Controllers/LocalesController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using SistemaPanera.Application.Models;
using SistemaPanera.Application.Models.ViewModels;
using SistemaPanera.BLL.Service;
using SistemaPanera.Models;
using System.Diagnostics;

namespace SistemaPanera.Application.Controllers
{
    [Authorize]
    public class LocalesController : Controller
    {
        private readonly ILocalService _LocalService;
        private readonly IProvinciaService _provinciaService;

        public LocalesController(ILocalService LocalService)
        {
            _LocalService = LocalService;
        }

        public IActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> Lista(int IdUnidadNegocio)
        {
            var Locales = await _LocalService.ObtenerTodos();

            var lista = Locales.Select(c => new VMLocal
            {
                Id = c.Id,
                Nombre = c.Nombre,
                IdUnidadNegocio = c.IdUnidadNegocio,
                UnidadNegocio = c.IdUnidadNegocioNavigation.Nombre,
            }).Where(x => x.IdUnidadNegocio == IdUnidadNegocio || IdUnidadNegocio == -1).ToList();

            return Ok(lista);
        }



        [HttpPost]
        public async Task<IActionResult> Insertar([FromBody] VMLocal model)
        {
            var Local = new Local
            {
                Id = model.Id,
                Nombre = model.Nombre,
                IdUnidadNegocio = model.IdUnidadNegocio
            };

            bool respuesta = await _LocalService.Insertar(Local);

            return Ok(new { valor = respuesta });
        }

        [HttpPut]
        public async Task<IActionResult> Actualizar([FromBody] VMLocal model)
        {
            var Local = new Local
            {
                Id = model.Id,
                Nombre = model.Nombre,
                IdUnidadNegocio = model.IdUnidadNegocio
            };

            bool respuesta = await _LocalService.Actualizar(Local);

            return Ok(new { valor = respuesta });
        }

        [HttpDelete]
        public async Task<IActionResult> Eliminar(int id)
        {
            bool respuesta = await _LocalService.Eliminar(id);

            return StatusCode(StatusCodes.Status200OK, new { valor = respuesta });
        }

        [HttpGet]
        public async Task<IActionResult> EditarInfo(int id)
        {
            var Local = await _LocalService.Obtener(id);

            if (Local != null)
            {
                return StatusCode(StatusCodes.Status200OK, Local);
            }
            else
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
        }
        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaPanera.Application/Controllers/UsuariosController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using SistemaPanera.Application.Models;
using SistemaPanera.Application.Models.ViewModels;
using SistemaPanera.BLL.Service;
using SistemaPanera.Models;
using System.Diagnostics;

namespace SistemaPanera.Application.Controllers
{
    [Authorize]
    public class UsuariosController : Controller
    {
        private readonly IUsuariosService _Usuarioservice;
        private readonly SessionHelper _sessionHelper;  // Inyección de SessionHelper

        public UsuariosController(IUsuariosService Usuarioservice)
        {
            _Usuarioservice = Usuarioservice;
        }

        public IActionResult Index()
        {
            return View();
        }


        public async Task<IActionResult> Configuracion()
        {
            // Obtener el usuario actual desde la sesión usando el helper inyectado
            var userSession = await SessionHelper.GetUsuarioSesion(HttpContext);

            // Si no se pudo obtener el usuario de la sesión
            if (userSession == null)
            {
                return RedirectToAction("Login", "Index");
            }

            // Obtener los detalles del usuario desde la base de datos
            var user = await _Usuarioservice.Obtener(userSession.Id);

            // Si el usuario no existe, redirigir al login
            if (user == null)
            {
                return RedirectToAction("Login", "Index");
            }

            // Pasar los datos del usuario a la vista
            return View(user);
        }

        [HttpGet]
        public async Task<IActionResult> Lista()
        {
            var Usuarios = await _Usuarioservice.ObtenerTodos();

            var lista = Usuarios.Select(c => new VMUser
            {
                Id = c.Id,
                Usuario = c.Usuario,
                Nombre = c.Nombre,
                Apellido = c.Apellido,
                Dni = c.Dni,
                Telefono = c.Telefono,
                Direccion = c.Direccion,
                IdRol = c.IdRol,
                Rol = c.IdRolNavigation.Nombre,
                IdEstado = c.IdEstado,
                Estado = c.IdEstadoNavigation.Nombre,
            }).ToList();

            return Ok(lista);
        }


        [HttpPost]
        public async Task<IActionResult> Insertar([FromBody] VMUser model)
        {

            var passwordHasher = new PasswordHasher<User>();


            var Usuario = new User
            {
                Usuario = model.Usuario,
                Nombre = model.Nombre,
                Apellido = model.Apellido,
                Dni = model.Dni,
                Telefono = model.Telefono,
                Direccion = model.Direccion,
                IdRol = model.IdRol,
                IdEstado = model.IdEstado,
                Contrasena = passwordHasher.HashPassword(null, model.Contrasena)
            };

            bool respuesta = await _Usuarioservice.Insertar(Usuario);

            return Ok(new { valor = respuesta });
        }

        [HttpPut]
        public async Task<IActionResult> Actualizar([FromBody] VMUser model)
        {
            var passwordHasher = new PasswordHasher<User>();

            // Obtiene el usuario de la base de datos
            User userbase = await _Usuarioservice.Obtener(model.Id);

            User nombreUsuario = await _Usuarioservice.ObtenerUsuario(model.Usuario);

            if (nombreUsuario != null && nombreUsuario.Id != model.Id)
            {
                return Ok(new { valor = "Usuario" });
            }

                if (model.CambioAdmin != 1) //YA QUE DESDE EL EDITAR DESDE EL ADMIN, NO VAMOS A MANDARLE LA CONTRASENA, SE LA CAMBIA DE UNA
            {
                var result = passwordHasher.VerifyHashedPassword(null, userbase.Contrasena, model.Contrasena);
                if (result != PasswordVerificationResult.Success)
                {
                    return Ok(new { valor = "Contrasena" });
                }
            }

            // Si se proporciona una contraseña nueva, úsala; de lo contrario, mantén la contraseña actual
            var passnueva = !string.IsNullOrEmpty(model.ContrasenaNueva)
                ? passwordHasher.HashPassword(null, model.ContrasenaNueva) // Hashea la nueva contraseña si es proporcionada
                : userbase.Contrasena; // Mantén la contraseña actual si no se proporciona una nueva

            // Actualiza las propiedades del objeto ya cargado
            userbase.Nombre = model.Nombre;
            userbase.Usuario = model.Usuario;
            userbase.Apellido = model.Apellido;
            userbase.Dni = model.Dni;
            userbase.Telefono = model.Telefono;
            userbase.Direccion = model.Direccion;
            userbase.IdRol = model.IdRol;
            userbase.IdEstado = model.IdEstado;
            userbase.Contrasena = passnueva; // Asigna la nueva contraseña hasheada

            // Realiza la actualización en la base de datos
            bool respuesta = await _Usuarioservice.Actualizar(userbase);

            return Ok(new { valor = respuesta ? "OK" : "Error" });
        }




        [HttpDelete]
        public async Task<IActionResult> Eliminar(int id)
        {
            bool respuesta = await _Usuarioservice.Eliminar(id);

            return StatusCode(StatusCodes.Status200OK, new { valor = respuesta });
        }

        [HttpGet]
        public async Task<IActionResult> EditarInfo(int id)
        {
            var Usuario = await _Usuarioservice.Obtener(id);

            if (Usuario != null)
            {
                return StatusCode(StatusCodes.Status200OK, Usuario);
            }
            else
            {
                return StatusCode(StatusCodes.Status404NotFound);
            }
        }




        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

SistemaPanera.Application/Views/Shared/Partials/NavBarLogin.cshtml
<link href="~/css/navbarlogin.css" rel="stylesheet" />


<nav class="navbar navbar-expand-lg navbar-light" style="background-color: rgba(112, 112, 112, 0.1);">
    <div class="container-fluid">
        <a class="navbar-brand">Sistema Sushiclub</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Proveedores")">Proveedores</a>
                </li>
              
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Insumos")">Insumos</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "ProveedoresInsumos")">Insumos Proveedores</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "SubRecetas")">Subrecetas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Recetas")">Recetas</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "OrdenesCompra")">Ordenes de Compra</a>
                </li>
                @* <li class="nav-item">
                    <a class="nav-link" href="@Url.Action("Index", "Compras")">Compras</a>
                </li> *@
                <li class="nav-item dropdown" id="configDropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="configDropdownLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        Configuraciones
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="configDropdownLink">
                        <li><a class="dropdown-item" href="@Url.Action("Index", "Locales")">Locales</a></li>
                        <li><a class="dropdown-item" href="@Url.Action("Index", "Usuarios")">Usuarios</a></li>
                        <li><a class="dropdown-item" onclick="abrirConfiguraciones()">Otras</a></li>
                    </ul>
                </li>
            </ul>

            <!-- Usuario Dropdown -->
            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle d-flex align-items-center" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-lg me-2" id="userName"></i> <!-- Ícono de Font Awesome 4.7 -->
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="userDropdown">
                        <li><a class="dropdown-item" href="#" onclick="window.location.href='/Usuarios/Configuracion';">Configuración</a></li>
                        <li><a class="dropdown-item" href="#" onclick="window.location.href='/Login/Logout';">Cerrar Sesión</a></li>
                    </ul>
                </li>
            </ul>
        </div>
    </div>
</nav>


 <!-- Modal Configuraciones -->
    <div class="modal fade" id="modalConfiguracion" tabindex="-1" role="dialog" aria-labelledby="modalConfiguracionLabel" aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="modalConfiguracionLabel">Configuracion</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>

                <label id="lblListaVacia" for="txtListaVacia" class="lblNombreInput" hidden></label>

                <div class="list-container">
                    <div id="configuracion-list">
                        <!-- Lista de categorías se llenará dinámicamente -->
                    </div>
                </div>

                <div id="contenedorNombreConfiguracion" class="form-group" hidden>
                    <label id="lblNombre" for="txtNombre" class="lblNombreInput">Nombre</label>
                    <input type="text" class="input-nuevomodif" id="txtNombreConfiguracion" required>
                    <input type="text" class="input-nuevomodif" id="txtIdConfiguracion" hidden>


                    <div class="btnModificarConfiguracion-container">
                        <button id="btnRegistrarModificarConfiguracion" class="btnModificarConfiguracion" onclick="guardarCambiosConfiguracion()">Modificar</button>
                        <button class="btnCancelarConfiguracion ml-2" onclick="cancelarModificarConfiguracion()">Cancelar</button>
                    </div>
                </div>

                <div class="btnAgregarConfiguracion-container">
                    <button id="agregarConfiguracion" class="btnAgregarConfiguracion" onclick="agregarConfiguracion()">Añadir</button>
                </div>

                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
                </div>
            </div>
        </div>
    </div>

<!-- Modal Configuraciones -->
<div class="modal fade" id="ModalEdicionConfiguraciones" tabindex="-1" role="dialog" aria-labelledby="ModalEdicionConfiguracionesLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="ModalEdicionConfiguracionesLabel">Configuraciones</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <form>
                    <button type="button" class="btnConfiguraciones" onclick="abrirConfiguracion('Unidad de negocio', 'UnidadesNegocio')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Categorias" class="imgConfiguraciones">
                        <span>Unidades de negocio</span>
                    </button>
                    <button type="button" class="btnConfiguraciones" onclick="abrirConfiguracion('Unidad de Medida', 'UnidadesMedida')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Unidad Medida" class="imgConfiguraciones">
                        <span>Unidades de medida</span>
                    </button>
                    <button type="button" class="btnConfiguraciones" onclick="abrirConfiguracion('Insumo Categoria', 'InsumosCategoria')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Categorias" class="imgConfiguraciones">
                        <span>Insumos Categorias</span>
                    </button>
                    <button type="button" class="btnConfiguraciones" onclick="abrirConfiguracion('Subreceta Categoria', 'SubrecetasCategoria')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Categorias" class="imgConfiguraciones">
                        <span>Subrecetas Categorias</span>
                    </button>
                    <button type="button" class="btnConfiguraciones" onclick="abrirConfiguracion('Receta Categoria', 'RecetasCategoria')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Categorias" class="imgConfiguraciones">
                        <span>Recetas Categorias</span>
                    </button>
                    <button type="button" class="btnConfiguraciones" onclick="abrirConfiguracion('Receta Tipo', 'RecetasTipo')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Categorias" class="imgConfiguraciones">
                        <span>Recetas Tipos</span>
                    </button>
                    <button type="button" class="btnConfiguraciones mt-2" onclick="abrirConfiguracion('Rol', 'Roles')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Roles" class="imgConfiguraciones">
                        <span>Roles</span>
                    </button>
                    <button type="button" class="btnConfiguraciones mt-2" onclick="abrirConfiguracion('Estados', 'OrdenesComprasEstado')">
                        <img src="/Imagenes/Configuracion.png" alt="Icono Roles" class="imgConfiguraciones">
                        <span>O. de Compra Estados</span>
                    </button>
                    @* <button type="button" class="btnConfiguraciones mt-2" onclick="abrirConfiguracion('Estados de Usuarios', 'EstadosUsuarios')">
                    <img src="/Imagenes/Roles.png" alt="Icono Roles" class="imgConfiguraciones">
                    <span>Estados de Usuarios</span>
                    </button> *@

                </form>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
            </div>
        </div>
    </div>
</div>

<script src="~/js/NavBarLogin.js?v=1.0" asp-append-version="true"></script>